name: fedo_musiqi_pro
description: Fedo Musiqi Pro
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^7.0.0
  url_launcher: ^6.2.0

flutter:
  uses-material-design: true
